### PR TITLE
Add tests & automated testing with Sauce Labs

### PR DESCRIPTION
**Pull request by feross**
Adds a couple basic tests, and adds files for travis and zuul.

Don't have write access to merge this myself. Also, someone needs to set up a hook for Travis.

### CODE REVIEW

**Comment by rauchg** [comment]
such speed wow

**Comment by feross** [comment]
Sauce labs badge won't render correctly until the travis hook is set up and someone does a commit.

**Comment by rauchg** [comment]
hook seems set up? 

image

**Comment by rauchg** [comment]
image

**Comment by rauchg** [comment]
i'll try a commit

**Comment by TooTallNate** [comment]
I just enabled it like 5 minutes ago. Sorry, forgot to ping back.

**Pull request merged**
